### ISSUE TITLE
search by ITU or DS

### ISSUE THREAD

**Issue by cragia** [ersel/country-code-info#1]
Hello.
I noticed a problem when searching by ITU, or other fields like DS. If I search for example for the ITU "I", it gets me the first country that CONTAINS the letter "I" and not the country I was searching for, that was "Italy".
I already know how to correct this, if I could contribute to the branch I can already push a solution...
Or anyway can you fix this issue?

thank you.

**Comment by ersel** [comment]
Feel free to open a pull request @cragia, I would be happy to accept if you've a test scenario around it 

https://help.github.com/articles/creating-a-pull-request/

**Comment by cragia** [comment]
ok, done.
I hope that I've done this correctly, it's the first time I contribute to a project. :)

**Comment by ersel** [comment]
Thanks @cragia , I'll review and merge.

**Comment by ersel** [comment]
This has been resolved by #3 , thanks for your contribution @cragia .
