### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by BuildWithLal** [ersel/country-code-info#4]
When i try to build with `npm run build`, this happens

```
react-scripts build
Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:  ./node_modules/country-code-info/index.js:35 
Read more here: http://bit.ly/2tRViJ9
```

```
country-code-info=0.1.0
npm=6.2.0
Node=10.6.0
React=16.2.0 
```

I tried to uninstall and re-install `country-code-info` from github master as well with no success

**Comment by BuildWithLal** [comment]
I gave a try to this and it has everything related to phone number.
https://github.com/catamphetamine/libphonenumber-js

**Comment by ersel** [comment]
Hi @lalzada ,

I believe you're trying to use this library as part of a web app. `index.js` module does a node `require()` call to import the data file. 

I guess solution would involve updating your webpack config so json file gets loaded. Glad you could find an alternative library which can handle your use case.
