### ISSUE TITLE
South Korea or North Korea are not detected

### ISSUE THREAD

**Issue by peltomaa** [ersel/country-code-info#7]
Strings "South Korea" or "North Korea" are not detected.
Problems seems to be that "South Korea" is named "Korea, South" and "North Korea" is named "Korea, North" in https://github.com/ersel/country-code-info/blob/master/data/countries.json

**Comment by ersel** [comment]
Happy to accept a PR to rename them.

**Comment by supertouko** [comment]
PR submitted #8

**Comment by ersel** [comment]
Thanks for the contribution @supertouko . I will publish a new version tonight
